package com.coffee.beansfinder.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Consumer-friendly product summary DTO
 * Generated by LLM during crawl to help hobbyist coffee drinkers understand products
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ConsumerSummaryDTO {

    /**
     * Flavor direction based on processing method
     * e.g., "Clean & Bright" for washed, "Fruity & Bold" for natural
     */
    @JsonProperty("flavor_direction")
    private FlavorDirectionDTO flavorDirection;

    /**
     * Top 2 tasting notes in uppercase
     * e.g., "BLACKCURRANT & CHOCOLATE"
     */
    @JsonProperty("flavor_headline")
    private String flavorHeadline;

    /**
     * Context sentence based on flavor profile
     * e.g., "Fruity-forward with a rich, sweet finish"
     */
    @JsonProperty("flavor_context")
    private String flavorContext;

    /**
     * Practical guidance on how to enjoy this coffee
     * e.g., ["Pour-over, filter", "Morning coffee", "Best black"]
     */
    @JsonProperty("best_for")
    private List<String> bestFor;

    /**
     * LLM-generated one-liner description (max 25 words)
     * Uses sensory analogies like "Like drinking a..."
     */
    @JsonProperty("consumer_description")
    private String consumerDescription;

    /**
     * Consumer tags like Safe Bet, Adventurous, Popular Origin, etc.
     */
    private List<ConsumerTagDTO> tags;

    /**
     * Flavor direction nested DTO
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class FlavorDirectionDTO {
        private String icon;        // e.g., "☕"
        private String label;       // e.g., "Clean & Bright"
        private String description; // e.g., "Crisp, clear, what great coffee should taste like"
    }

    /**
     * Consumer tag nested DTO
     */
    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ConsumerTagDTO {
        private String icon;   // e.g., "🛡️"
        private String label;  // e.g., "Safe Bet"
    }
}
