-- Graphee Curious AI content system tables
-- CoffeeNews: stores RSS feed articles for digest generation
-- InstagramPosts: stores generated Instagram content with approval workflow

-- Coffee News table (RSS articles)
CREATE TABLE IF NOT EXISTS coffee_news (
    id BIGSERIAL PRIMARY KEY,
    source VARCHAR(100),
    title VARCHAR(500) NOT NULL,
    link VARCHAR(1000) UNIQUE,
    summary TEXT,
    published_at TIMESTAMP,
    fetched_at TIMESTAMP NOT NULL DEFAULT NOW(),
    content_hash VARCHAR(64)
);

CREATE INDEX IF NOT EXISTS idx_coffee_news_fetched ON coffee_news(fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_coffee_news_source ON coffee_news(source);

-- Instagram Posts table for Graphee Curious AI content system
-- Stores generated Instagram content with approval workflow

CREATE TABLE IF NOT EXISTS instagram_posts (
    id BIGSERIAL PRIMARY KEY,

    -- Content
    caption TEXT NOT NULL,
    image_url VARCHAR(1000),
    image_prompt TEXT,

    -- Source tracking
    source_type VARCHAR(50),                -- 'reddit', 'news', 'mixed'
    source_ids JSONB,                       -- Array of source IDs (Reddit post IDs, CoffeeNews IDs)

    -- Generation metadata
    content_hash VARCHAR(64),               -- Hash of input sources for deduplication
    generation_cost DECIMAL(6,4),           -- Cost tracking in USD

    -- Workflow status
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    scheduled_at TIMESTAMP,
    posted_at TIMESTAMP,
    instagram_media_id VARCHAR(100),        -- Instagram's media ID after posting

    -- Audit
    reviewed_by VARCHAR(100),
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP,

    CONSTRAINT chk_instagram_post_status CHECK (status IN ('draft', 'approved', 'scheduled', 'posted', 'rejected'))
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_instagram_posts_status ON instagram_posts(status);
CREATE INDEX IF NOT EXISTS idx_instagram_posts_scheduled ON instagram_posts(scheduled_at) WHERE status = 'scheduled';
CREATE INDEX IF NOT EXISTS idx_instagram_posts_created ON instagram_posts(created_at DESC);

COMMENT ON TABLE instagram_posts IS 'Instagram content generated by Graphee Curious AI';
COMMENT ON COLUMN instagram_posts.source_ids IS 'JSON array of Reddit post IDs or CoffeeNews article IDs used to generate this content';
COMMENT ON COLUMN instagram_posts.status IS 'Workflow status: draft -> approved/rejected -> scheduled -> posted';
